version: "3"
services:
  dev_container:
    build:
      context: ".devcontainer"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:dev@postgres:5432/sce
      PGUSER: postgres
      PGPASSWORD: dev
      PGHOST: postgres
      PGDATABASE: sce
      DEV: true
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: sce
  migration:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: dockerfiles/sql-migration.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_HOST: postgres
      POSTGRES_DB: sce
  postgraphile:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: dockerfiles/postgraphile.dockerfile
    environment:
      PGUSER: postgres
      PGPASSWORD: dev
      PGHOST: postgres
      PGDATABASE: sce
    command:
      [
        "--no-ignore-rbac",
        "--cors",
        "--retry-on-init-fail",
        "--owner-connection",
        "postgres://postgres:dev@postgres:5432/sce",
        "--schema",
        "public",
        "--append-plugins",
        "@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,postgraphile-plugin-nested-mutations,@graphile-contrib/pg-many-to-many",
        "--enhance-graphiql",
        "--watch",
      ]
    ports: ["5001:5000"]
