env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: "latest"
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  complexity:
    - error
    - 10
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn